"""Markdown export (Obsidian-friendly)."""

from __future__ import annotations

from src.analysis.report import GapReportOutput


def to_markdown(report: GapReportOutput) -> str:
    slug = report.company_name.lower().replace(" ", "-")
    tags = ["cit", "company-intel", report.data_quality, report.confidence]
    if report.enrichment_applied:
        tags.append("enriched")

    fm = "---\n"
    fm += f'title: "CIT — {report.company_name}"\n'
    fm += f"company: {report.company_name}\n"
    fm += f"analyzed: {report.analyzed_at}\n"
    fm += f"confidence: {report.confidence}\n"
    fm += f"data_quality: {report.data_quality}\n"
    fm += f"synthesis: {report.synthesis_mode}\n"
    fm += "tags:\n" + "".join(f"  - {t}\n" for t in tags)
    fm += "---\n\n"

    body = [
        f"# {report.company_name}",
        "",
        f"> **Key tension:** {report.key_tension}",
        "",
        "## Interview insight",
        "",
        report.interview_insight,
        "",
        "## Layer 1 — What they say",
        "",
        report.what_company_says,
        "",
        "<details><summary>Raw Layer 1 narrative</summary>",
        "",
        report.layer1_summary,
        "",
        "</details>",
        "",
        "## Layer 2 — What data shows",
        "",
        report.what_data_shows,
        "",
        "<details><summary>Raw Layer 2 signals</summary>",
        "",
        report.layer2_summary,
        "",
        "</details>",
        "",
        "## Gaps",
        "",
    ]

    if not report.gaps:
        body.append("_No gaps detected._")
    else:
        for g in report.gaps:
            sev = g.get("severity", "low")
            body.extend([
                f"### [{sev.upper()}] {g.get('category', 'gap')}",
                "",
                f"- **Claim:** {g.get('claim', '')}",
                f"- **Reality:** {g.get('reality', '')}",
            ])
            if g.get("note"):
                body.append(f"- **Note:** {g['note']}")
            body.append("")

    body.extend([
        "## Talking points",
        "",
    ])
    for tp in report.talking_points:
        body.append(f"- [ ] {tp}")

    if report.edge_flags or report.edge_warnings:
        body.extend(["", "## Edge cases", ""])
        for f in report.edge_flags:
            body.append(f"- Flag: `{f}`")
        for w in report.edge_warnings:
            body.append(f"- {w}")

    body.extend([
        "",
        "## Metadata",
        "",
        f"- Sources: {', '.join(report.data_sources) or 'none'}",
        f"- Enrichment: {'yes' if report.enrichment_applied else 'no'}",
        "",
        "---",
        f"_Generated by CIT at {report.analyzed_at}_",
    ])

    return fm + "\n".join(body)
