"""Markdown export — v2 with sparse-aware layout and no collapsed sections."""

from __future__ import annotations

from src.analysis.report import GapReportOutput


def to_markdown(report: GapReportOutput) -> str:
    slug = report.company_name.lower().replace(" ", "-")
    tags = ["cit", "company-intel", report.data_quality, report.confidence]
    if report.enrichment_applied:
        tags.append("enriched")

    is_sparse = report.data_quality == "sparse" or report.confidence == "low"
    has_gaps = len(report.gaps) > 0

    fm = "---\n"
    fm += f'title: "CIT — {report.company_name}"\n'
    fm += f"company: {report.company_name}\n"
    fm += f"analyzed: {report.analyzed_at}\n"
    fm += f"confidence: {report.confidence}\n"
    fm += f"data_quality: {report.data_quality}\n"
    fm += f"synthesis: {report.synthesis_mode}\n"
    fm += "tags:\n" + "".join(f"  - {t}\n" for t in tags)
    fm += "---\n\n"

    body = [
        f"# {report.company_name}",
        "",
        f"> **Key tension:** {report.key_tension}",
        "",
        "## Interview insight",
        "",
        report.interview_insight,
        "",
        "## What they say vs. what data shows",
        "",
        "| | |",
        "|---|---|",
        f"| **Narrative** | {report.what_company_says} |",
        f"| **Data** | {report.what_data_shows} |",
        "",
    ]

    if is_sparse and not has_gaps:
        body.extend(
            [
                "## Probes for limited-data companies",
                "",
                "Public data on this company is limited. Use these questions in conversation:",
                "",
                "- What core product or service drives revenue? (no public breakdown available)",
                "- Are they growing headcount? Check recent job postings or LinkedIn growth",
                "- Who are their key customers or partners? Look for case studies or press releases",
                "- What recent hires or board changes signal strategic direction?",
                "",
            ]
        )

    body.append("## Gaps")
    body.append("")

    if not has_gaps:
        if is_sparse:
            body.append(
                "Not enough public data to detect structural gaps. Use the probes above."
            )
        else:
            body.append("No material gaps detected at this level of analysis.")
    else:
        for g in report.gaps:
            sev = g.get("severity", "low")
            icon = {"high": "!", "medium": "~", "low": "."}.get(sev, ".")
            body.extend(
                [
                    f"### [{sev.upper()}] {g.get('category', 'gap')}",
                    "",
                    f"- **Claim:** {g.get('claim', '')}",
                    f"- **Reality:** {g.get('reality', '')}",
                ]
            )
            if g.get("note"):
                body.append(f"- **Note:** {g['note']}")
            body.append("")

    body.extend(
        [
            "## Talking points",
            "",
        ]
    )

    if report.talking_points:
        for tp in report.talking_points:
            body.append(f"- [ ] {tp}")
    elif is_sparse:
        body.append("- [ ] Data limited — lead with questions, not assertions")
    else:
        body.append("- [ ] No talking points generated")

    if report.edge_flags or report.edge_warnings:
        body.extend(["", "## Edge cases", ""])
        for f in report.edge_flags:
            body.append(f"- Flag: `{f}`")
        for w in report.edge_warnings:
            body.append(f"- {w}")

    body.extend(
        [
            "",
            "## Metadata",
            "",
            f"- Sources: {', '.join(report.data_sources) or 'none'}",
            f"- Enrichment: {'yes' if report.enrichment_applied else 'no'}",
            "",
            "---",
            f"_Generated by CIT at {report.analyzed_at}_",
        ]
    )

    return fm + "\n".join(body)
