"""Single-file HTML report with scorecard, filters, and reframing bridge."""

from __future__ import annotations

import html
import json

from src.analysis.report import GapReportOutput
from .theme import CIT_CSS, CIT_JS, SEVERITY_COLORS, QUALITY_PCT, CONFIDENCE_PCT


def to_html(report: GapReportOutput, *, title: str | None = None) -> str:
    title = title or f"CIT — {report.company_name}"
    gaps_json = json.dumps(report.gaps)

    gap_cards = _gap_cards_html(report.gaps)
    radar_bars = _gap_radar(report.gaps)
    checklist = _checklist_html(report.talking_points)
    warnings = _warnings_html(report)
    scorecard = _scorecard_html(report)
    flags = "".join(f'<span class="chip warn">{html.escape(f)}</span>' for f in report.edge_flags)

    meta_chips = [
        f'<span class="chip">quality: {html.escape(report.data_quality)}</span>',
        f'<span class="chip">synthesis: {html.escape(report.synthesis_mode)}</span>',
    ]
    if report.enrichment_applied:
        meta_chips.append('<span class="chip accent">reference enriched</span>')

    insight_text = report.interview_insight

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{html.escape(title)}</title>
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;600;700&display=swap" rel="stylesheet" />
  <style>{CIT_CSS}</style>
</head>
<body data-theme="dark">
  <div class="wrap">
    <header class="topbar">
      <div>
        <div class="brand">Company Intelligence Tool</div>
        <h1>{html.escape(report.company_name)}</h1>
        <p class="sub">Reframing report · {html.escape(report.analyzed_at[:19].replace('T', ' '))} UTC</p>
      </div>
      <div class="toolbar">
        <button class="btn" onclick="window.print()">Print</button>
        <button class="btn" id="copy-btn" onclick="copyInsight()">Copy insight</button>
        <button class="btn" onclick="toggleTheme()">Theme</button>
      </div>
    </header>

    <nav class="nav-pills">
      <a href="#insight">Insight</a>
      <a href="#layers">Layers</a>
      <a href="#gaps">Gaps</a>
      <a href="#prep">Prep</a>
    </nav>

    {scorecard}

    <div class="chips" style="margin-bottom:1rem">
      {''.join(meta_chips)}
      {flags}
      <span class="chip">sources: {html.escape(', '.join(report.data_sources) or '—')}</span>
    </div>

    {warnings}

    <div class="insight-box" id="insight">
      <h2>Interview insight</h2>
      <p class="tension">{html.escape(report.key_tension)}</p>
      <p class="insight-body" id="insight-text">{html.escape(insight_text)}</p>
    </div>

    <div class="reframe-bridge" id="layers">
      <div class="layer layer1">
        <h3>Layer 1 — Narrative</h3>
        <p>{html.escape(report.what_company_says)}</p>
      </div>
      <div class="bridge-arrow" title="Reframing gap">⟷</div>
      <div class="layer layer2">
        <h3>Layer 2 — Data</h3>
        <p>{html.escape(report.what_data_shows)}</p>
      </div>
    </div>

    <section id="gaps">
      <h2>Gap analysis <span class="muted" style="font-weight:400">({len(report.gaps)} detected)</span></h2>
      <div class="radar">{radar_bars}</div>
      <div class="gap-filters">
        <button class="btn active" data-filter="all" onclick="filterGaps('all')">All</button>
        <button class="btn" data-filter="high" onclick="filterGaps('high')">High</button>
        <button class="btn" data-filter="medium" onclick="filterGaps('medium')">Medium</button>
        <button class="btn" data-filter="low" onclick="filterGaps('low')">Low</button>
      </div>
      <div class="gaps-grid">{gap_cards or '<p class="muted">No structural gaps detected — probe with second-order questions.</p>'}</div>
    </section>

    <section id="prep">
      <h2>Interview prep checklist</h2>
      <ul class="checklist">{checklist}</ul>
    </section>

    <footer>Generated by CIT · confidence {html.escape(report.confidence)} · {html.escape(report.synthesis_mode)} synthesis</footer>
  </div>
  <script>const gaps = {gaps_json};{CIT_JS}</script>
</body>
</html>"""


def _scorecard_html(report: GapReportOutput) -> str:
    conf_pct = CONFIDENCE_PCT.get(report.confidence, 50)
    qual_pct = QUALITY_PCT.get(report.data_quality, 40)
    high = sum(1 for g in report.gaps if g.get("severity") == "high")
    gap_score = min(100, len(report.gaps) * 25 + high * 15)

    def stat(label: str, val: str, pct: int, color: str) -> str:
        return f"""
        <div class="stat">
          <label>{html.escape(label)}</label>
          <div class="val">{html.escape(val)}</div>
          <div class="bar"><div style="width:{pct}%;background:{color}"></div></div>
        </div>"""

    return f"""<div class="scorecard">
      {stat("Confidence", report.confidence, conf_pct, "#3b82f6")}
      {stat("Data quality", report.data_quality, qual_pct, "#34d399")}
      {stat("Gaps found", str(len(report.gaps)), gap_score, "#a78bfa")}
      {stat("High severity", str(high), min(100, high * 40), "#ef4444")}
    </div>"""


def _gap_cards_html(gaps: list[dict]) -> str:
    parts = []
    for g in gaps:
        sev = g.get("severity", "low")
        color = SEVERITY_COLORS.get(sev, "#94a3b8")
        parts.append(f"""
        <article class="gap-card" data-severity="{html.escape(sev)}">
          <header>
            <span class="severity-dot" style="background:{color}"></span>
            <span class="gap-cat">{html.escape(g.get('category', 'gap'))}</span>
            <span class="severity-badge">{html.escape(sev)}</span>
          </header>
          <p><strong>Claim</strong> — {html.escape(g.get('claim', ''))}</p>
          <p><strong>Reality</strong> — {html.escape(g.get('reality', ''))}</p>
          {f'<p class="note">{html.escape(g["note"])}</p>' if g.get('note') else ''}
        </article>""")
    return "".join(parts)


def _gap_radar(gaps: list[dict]) -> str:
    counts = {"high": 0, "medium": 0, "low": 0}
    for g in gaps:
        counts[g.get("severity", "low")] = counts.get(g.get("severity", "low"), 0) + 1
    max_c = max(counts.values()) if gaps else 1
    parts = []
    for sev, color in SEVERITY_COLORS.items():
        c = counts.get(sev, 0)
        pct = (c / max_c * 100) if max_c else 0
        parts.append(f"""
        <div class="radar-row">
          <span class="radar-label">{sev}</span>
          <div class="radar-bar"><div class="radar-fill" style="width:{pct}%;background:{color}"></div></div>
          <span>{c}</span>
        </div>""")
    return "".join(parts)


def _checklist_html(points: list[str]) -> str:
    if not points:
        return "<li class='muted'>No talking points generated</li>"
    return "".join(
        f'<li><label><input type="checkbox" /> {html.escape(tp)}</label></li>'
        for tp in points
    )


def _warnings_html(report: GapReportOutput) -> str:
    if not report.edge_warnings:
        return ""
    items = "".join(f"<li>{html.escape(w)}</li>" for w in report.edge_warnings)
    return f'<div class="warnings"><strong>Edge-case notes</strong><ul>{items}</ul></div>'
